version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: vendure-postgres
    environment:
      POSTGRES_USER: vendure
      POSTGRES_PASSWORD: vendure
      POSTGRES_DB: vendure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vendure-network

  redis:
    image: redis:7-alpine
    container_name: vendure-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vendure-network

  adminer:
    image: adminer
    container_name: vendure-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - vendure-network

volumes:
  postgres_data:
  redis_data:

networks:
  vendure-network:
    driver: bridge